name: zabb
description: Flutter-based mobile client for Zabbix monitoring
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.10
  url_launcher: ^6.2.5
  audioplayers: ^6.0.0
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/zabb.svg
    - assets/nymfette3-smile.png
    - assets/sounds/
